version: "3.5"
services:
  db:
    image: rodrigodoe/zup-bank-db
    build:
      context: .
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: zup-bank-db
    ports:
      - "3306:3306"
    networks:
      - zup
networks:
  zup:
    driver: bridge